export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const RESET_STATE = 'RESET_STATE';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const ADD_COVER_PHOTO_REQUEST = 'ADD_COVER_PHOTO_REQUEST';
export const ADD_COVER_PHOTO_SUCCESS = 'ADD_COVER_PHOTO_SUCCESS';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';

export const CREATE_USER_TWEET_REQUEST = 'CREATE_USER_TWEET_REQUEST';
export const CREATE_USER_TWEET_SUCCESS = 'CREATE_USER_TWEET_SUCCESS';

export const CREATE_USER_RETWEET_REQUEST = 'CREATE_USER_RETWEET_REQUEST';
export const CREATE_USER_RETWEET_SUCCESS = 'CREATE_USER_RETWEET_SUCCESS';

export const GET_ALL_TWEET_REQUEST = 'GET_ALL_TWEET_REQUEST';
export const GET_ALL_TWEET_SUCCESS = 'GET_ALL_TWEET_SUCCESS';

export const USER_COMMENT_REQUEST = 'USER_COMMENT_REQUEST';
export const USER_COMMENT_SUCCESS = 'USER_COMMENT_SUCCESS';

export const SAVE_TWEET_REQUEST = 'SAVE_TWEET_REQUEST';
export const SAVE_TWEET_SUCCESS = 'SAVE_TWEET_SUCCESS';
